services:
  backend:
    build:
      context: ./chatroom-go
      dockerfile: Dockerfile
    container_name: chatroom-backend
    ports:
      - "8080:8080"
    networks:
      - chatnet

  frontend:
    build:
      context: ./chatroom-react
      dockerfile: Dockerfile
    container_name: chatroom-frontend
    ports:
      - "80:80"
    networks:
      - chatnet
    depends_on:
      - backend

networks:
  chatnet:
    driver: bridge
